AnimationExtraPointers:
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
	dw TangelaAnimationExtra
