FramesPointers:
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
	dw TangelaFrames
