
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	
	; Unown pics have their own table. See UnownPicPointers
	dbw -1, -1
	dbw -1, -1
	
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	add_pic TangelaFrontpic
	add_pic TangelaBackpic
	dbw -1, -1 ; unused
	dbw -1, -1 ; unused
	add_pic EggPic
	dbw -1, -1 ; unused
