UnownAnimationPointers:
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
	dw TangelaAnimation
