UnownBitmasksPointers:
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
	dw TangelaBitmasks
