; f2787
;                               index,          pitch, length
BulbasaurCryHeader:   cry_header CRY_GOLEM,       $000,  $100
IvysaurCryHeader:     cry_header CRY_GOLEM,       $000,  $100
VenusaurCryHeader:    cry_header CRY_GOLEM,       $000,  $100
CharmanderCryHeader:  cry_header CRY_GOLEM,       $000,  $100
CharmeleonCryHeader:  cry_header CRY_GOLEM,       $000,  $100
CharizardCryHeader:   cry_header CRY_GOLEM,       $000,  $100
SquirtleCryHeader:    cry_header CRY_GOLEM,       $000,  $100
WartortleCryHeader:   cry_header CRY_GOLEM,       $000,  $100
BlastoiseCryHeader:   cry_header CRY_GOLEM,       $000,  $100
CaterpieCryHeader:    cry_header CRY_GOLEM,       $000,  $100
MetapodCryHeader:     cry_header CRY_GOLEM,       $000,  $100
ButterfreeCryHeader:  cry_header CRY_GOLEM,       $000,  $100
WeedleCryHeader:      cry_header CRY_GOLEM,       $000,  $100
KakunaCryHeader:      cry_header CRY_GOLEM,       $000,  $100
BeedrillCryHeader:    cry_header CRY_GOLEM,       $000,  $100
PidgeyCryHeader:      cry_header CRY_GOLEM,       $000,  $100
PidgeottoCryHeader:   cry_header CRY_GOLEM,       $000,  $100
PidgeotCryHeader:     cry_header CRY_GOLEM,       $000,  $100
RattataCryHeader:     cry_header CRY_GOLEM,       $000,  $100
RaticateCryHeader:    cry_header CRY_GOLEM,       $000,  $100
SpearowCryHeader:     cry_header CRY_GOLEM,       $000,  $100
FearowCryHeader:      cry_header CRY_GOLEM,       $000,  $100
EkansCryHeader:       cry_header CRY_GOLEM,       $000,  $100
ArbokCryHeader:       cry_header CRY_GOLEM,       $000,  $100
PikachuCryHeader:     cry_header CRY_GOLEM,       $000,  $100
RaichuCryHeader:      cry_header CRY_GOLEM,       $000,  $100
SandshrewCryHeader:   cry_header CRY_GOLEM,       $000,  $100
SandslashCryHeader:   cry_header CRY_GOLEM,       $000,  $100
NidoranFCryHeader:    cry_header CRY_GOLEM,       $000,  $100
NidorinaCryHeader:    cry_header CRY_GOLEM,       $000,  $100
NidoqueenCryHeader:   cry_header CRY_GOLEM,       $000,  $100
NidoranMCryHeader:    cry_header CRY_GOLEM,       $000,  $100
NidorinoCryHeader:    cry_header CRY_GOLEM,       $000,  $100
NidokingCryHeader:    cry_header CRY_GOLEM,       $000,  $100
ClefairyCryHeader:    cry_header CRY_GOLEM,       $000,  $100
ClefableCryHeader:    cry_header CRY_GOLEM,       $000,  $100
VulpixCryHeader:      cry_header CRY_GOLEM,       $000,  $100
NinetalesCryHeader:   cry_header CRY_GOLEM,       $000,  $100
JigglypuffCryHeader:  cry_header CRY_GOLEM,       $000,  $100
WigglytuffCryHeader:  cry_header CRY_GOLEM,       $000,  $100
ZubatCryHeader:       cry_header CRY_GOLEM,       $000,  $100
GolbatCryHeader:      cry_header CRY_GOLEM,       $000,  $100
OddishCryHeader:      cry_header CRY_GOLEM,       $000,  $100
GloomCryHeader:       cry_header CRY_GOLEM,       $000,  $100
VileplumeCryHeader:   cry_header CRY_GOLEM,       $000,  $100
ParasCryHeader:       cry_header CRY_GOLEM,       $000,  $100
ParasectCryHeader:    cry_header CRY_GOLEM,       $000,  $100
VenonatCryHeader:     cry_header CRY_GOLEM,       $000,  $100
VenomothCryHeader:    cry_header CRY_GOLEM,       $000,  $100
DiglettCryHeader:     cry_header CRY_GOLEM,       $000,  $100
DugtrioCryHeader:     cry_header CRY_GOLEM,       $000,  $100
MeowthCryHeader:      cry_header CRY_GOLEM,       $000,  $100
PersianCryHeader:     cry_header CRY_GOLEM,       $000,  $100
PsyduckCryHeader:     cry_header CRY_GOLEM,       $000,  $100
GolduckCryHeader:     cry_header CRY_GOLEM,       $000,  $100
MankeyCryHeader:      cry_header CRY_GOLEM,       $000,  $100
PrimeapeCryHeader:    cry_header CRY_GOLEM,       $000,  $100
GrowlitheCryHeader:   cry_header CRY_GOLEM,       $000,  $100
ArcanineCryHeader:    cry_header CRY_GOLEM,       $000,  $100
PoliwagCryHeader:     cry_header CRY_GOLEM,       $000,  $100
PoliwhirlCryHeader:   cry_header CRY_GOLEM,       $000,  $100
PoliwrathCryHeader:   cry_header CRY_GOLEM,       $000,  $100
AbraCryHeader:        cry_header CRY_GOLEM,       $000,  $100
KadabraCryHeader:     cry_header CRY_GOLEM,       $000,  $100
AlakazamCryHeader:    cry_header CRY_GOLEM,       $000,  $100
MachopCryHeader:      cry_header CRY_GOLEM,       $000,  $100
MachokeCryHeader:     cry_header CRY_GOLEM,       $000,  $100
MachampCryHeader:     cry_header CRY_GOLEM,       $000,  $100
BellsproutCryHeader:  cry_header CRY_GOLEM,       $000,  $100
WeepinbellCryHeader:  cry_header CRY_GOLEM,       $000,  $100
VictreebelCryHeader:  cry_header CRY_GOLEM,       $000,  $100
TentacoolCryHeader:   cry_header CRY_GOLEM,       $000,  $100
TentacruelCryHeader:  cry_header CRY_GOLEM,       $000,  $100
GeodudeCryHeader:     cry_header CRY_GOLEM,       $000,  $100
GravelerCryHeader:    cry_header CRY_GOLEM,       $000,  $100
GolemCryHeader:       cry_header CRY_GOLEM,       $000,  $100
PonytaCryHeader:      cry_header CRY_GOLEM,       $000,  $100
RapidashCryHeader:    cry_header CRY_GOLEM,       $000,  $100
SlowpokeCryHeader:    cry_header CRY_GOLEM,       $000,  $100
SlowbroCryHeader:     cry_header CRY_GOLEM,       $000,  $100
MagnemiteCryHeader:   cry_header CRY_GOLEM,       $000,  $100
MagnetonCryHeader:    cry_header CRY_GOLEM,       $000,  $100
FarfetchDCryHeader:   cry_header CRY_GOLEM,       $000,  $100
DoduoCryHeader:       cry_header CRY_GOLEM,       $000,  $100
DodrioCryHeader:      cry_header CRY_GOLEM,       $000,  $100
SeelCryHeader:        cry_header CRY_GOLEM,       $000,  $100
DewgongCryHeader:     cry_header CRY_GOLEM,       $000,  $100
GrimerCryHeader:      cry_header CRY_GOLEM,       $000,  $100
MukCryHeader:         cry_header CRY_GOLEM,       $000,  $100
ShellderCryHeader:    cry_header CRY_GOLEM,       $000,  $100
CloysterCryHeader:    cry_header CRY_GOLEM,       $000,  $100
GastlyCryHeader:      cry_header CRY_GOLEM,       $000,  $100
HaunterCryHeader:     cry_header CRY_GOLEM,       $000,  $100
GengarCryHeader:      cry_header CRY_GOLEM,       $000,  $100
OnixCryHeader:        cry_header CRY_GOLEM,       $000,  $100
DrowzeeCryHeader:     cry_header CRY_GOLEM,       $000,  $100
HypnoCryHeader:       cry_header CRY_GOLEM,       $000,  $100
KrabbyCryHeader:      cry_header CRY_GOLEM,       $000,  $100
KinglerCryHeader:     cry_header CRY_GOLEM,       $000,  $100
VoltorbCryHeader:     cry_header CRY_GOLEM,       $000,  $100
ElectrodeCryHeader:   cry_header CRY_GOLEM,       $000,  $100
ExeggcuteCryHeader:   cry_header CRY_GOLEM,       $000,  $100
ExeggutorCryHeader:   cry_header CRY_GOLEM,       $000,  $100
CuboneCryHeader:      cry_header CRY_GOLEM,       $000,  $100
MarowakCryHeader:     cry_header CRY_GOLEM,       $000,  $100
HitmonleeCryHeader:   cry_header CRY_GOLEM,       $000,  $100
HitmonchanCryHeader:  cry_header CRY_GOLEM,       $000,  $100
LickitungCryHeader:   cry_header CRY_GOLEM,       $000,  $100
KoffingCryHeader:     cry_header CRY_GOLEM,       $000,  $100
WeezingCryHeader:     cry_header CRY_GOLEM,       $000,  $100
RhyhornCryHeader:     cry_header CRY_GOLEM,       $000,  $100
RhydonCryHeader:      cry_header CRY_GOLEM,       $000,  $100
ChanseyCryHeader:     cry_header CRY_GOLEM,       $000,  $100
TangelaCryHeader:     cry_header CRY_GOLEM,       $000,  $100
KangaskhanCryHeader:  cry_header CRY_GOLEM,       $000,  $100
HorseaCryHeader:      cry_header CRY_GOLEM,       $000,  $100
SeadraCryHeader:      cry_header CRY_GOLEM,       $000,  $100
GoldeenCryHeader:     cry_header CRY_GOLEM,       $000,  $100
SeakingCryHeader:     cry_header CRY_GOLEM,       $000,  $100
StaryuCryHeader:      cry_header CRY_GOLEM,       $000,  $100
StarmieCryHeader:     cry_header CRY_GOLEM,       $000,  $100
MrMimeCryHeader:      cry_header CRY_GOLEM,       $000,  $100
ScytherCryHeader:     cry_header CRY_GOLEM,       $000,  $100
JynxCryHeader:        cry_header CRY_GOLEM,       $000,  $100
ElectabuzzCryHeader:  cry_header CRY_GOLEM,       $000,  $100
MagmarCryHeader:      cry_header CRY_GOLEM,       $000,  $100
PinsirCryHeader:      cry_header CRY_GOLEM,       $000,  $100
TaurosCryHeader:      cry_header CRY_GOLEM,       $000,  $100
MagikarpCryHeader:    cry_header CRY_GOLEM,       $000,  $100
GyaradosCryHeader:    cry_header CRY_GOLEM,       $000,  $100
LaprasCryHeader:      cry_header CRY_GOLEM,       $000,  $100
DittoCryHeader:       cry_header CRY_GOLEM,       $000,  $100
EeveeCryHeader:       cry_header CRY_GOLEM,       $000,  $100
VaporeonCryHeader:    cry_header CRY_GOLEM,       $000,  $100
JolteonCryHeader:     cry_header CRY_GOLEM,       $000,  $100
FlareonCryHeader:     cry_header CRY_GOLEM,       $000,  $100
PorygonCryHeader:     cry_header CRY_GOLEM,       $000,  $100
OmanyteCryHeader:     cry_header CRY_GOLEM,       $000,  $100
OmastarCryHeader:     cry_header CRY_GOLEM,       $000,  $100
KabutoCryHeader:      cry_header CRY_GOLEM,       $000,  $100
KabutopsCryHeader:    cry_header CRY_GOLEM,       $000,  $100
AerodactylCryHeader:  cry_header CRY_GOLEM,       $000,  $100
SnorlaxCryHeader:     cry_header CRY_GOLEM,       $000,  $100
ArticunoCryHeader:    cry_header CRY_GOLEM,       $000,  $100
ZapdosCryHeader:      cry_header CRY_GOLEM,       $000,  $100
MoltresCryHeader:     cry_header CRY_GOLEM,       $000,  $100
DratiniCryHeader:     cry_header CRY_GOLEM,       $000,  $100
DragonairCryHeader:   cry_header CRY_GOLEM,       $000,  $100
DragoniteCryHeader:   cry_header CRY_GOLEM,       $000,  $100
MewtwoCryHeader:      cry_header CRY_GOLEM,       $000,  $100
MewCryHeader:         cry_header CRY_GOLEM,       $000,  $100
ChikoritaCryHeader:   cry_header CRY_GOLEM,       $000,  $100
BayleefCryHeader:     cry_header CRY_GOLEM,       $000,  $100
MeganiumCryHeader:    cry_header CRY_GOLEM,       $000,  $100
CyndaquilCryHeader:   cry_header CRY_GOLEM,       $000,  $100
QuilavaCryHeader:     cry_header CRY_GOLEM,       $000,  $100
TyphlosionCryHeader:  cry_header CRY_GOLEM,       $000,  $100
TotodileCryHeader:    cry_header CRY_GOLEM,       $000,  $100
CroconawCryHeader:    cry_header CRY_GOLEM,       $000,  $100
FeraligatrCryHeader:  cry_header CRY_GOLEM,       $000,  $100
SentretCryHeader:     cry_header CRY_GOLEM,       $000,  $100
FurretCryHeader:      cry_header CRY_GOLEM,       $000,  $100
HoothootCryHeader:    cry_header CRY_GOLEM,       $000,  $100
NoctowlCryHeader:     cry_header CRY_GOLEM,       $000,  $100
LedybaCryHeader:      cry_header CRY_GOLEM,       $000,  $100
LedianCryHeader:      cry_header CRY_GOLEM,       $000,  $100
SpinarakCryHeader:    cry_header CRY_GOLEM,       $000,  $100
AriadosCryHeader:     cry_header CRY_GOLEM,       $000,  $100
CrobatCryHeader:      cry_header CRY_GOLEM,       $000,  $100
ChinchouCryHeader:    cry_header CRY_GOLEM,       $000,  $100
LanturnCryHeader:     cry_header CRY_GOLEM,       $000,  $100
PichuCryHeader:       cry_header CRY_GOLEM,       $000,  $100
CleffaCryHeader:      cry_header CRY_GOLEM,       $000,  $100
IgglybuffCryHeader:   cry_header CRY_GOLEM,       $000,  $100
TogepiCryHeader:      cry_header CRY_GOLEM,       $000,  $100
TogeticCryHeader:     cry_header CRY_GOLEM,       $000,  $100
NatuCryHeader:        cry_header CRY_GOLEM,       $000,  $100
XatuCryHeader:        cry_header CRY_GOLEM,       $000,  $100
MareepCryHeader:      cry_header CRY_GOLEM,       $000,  $100
FlaaffyCryHeader:     cry_header CRY_GOLEM,       $000,  $100
AmpharosCryHeader:    cry_header CRY_GOLEM,       $000,  $100
BellossomCryHeader:   cry_header CRY_GOLEM,       $000,  $100
MarillCryHeader:      cry_header CRY_GOLEM,       $000,  $100
AzumarillCryHeader:   cry_header CRY_GOLEM,       $000,  $100
SudowoodoCryHeader:   cry_header CRY_GOLEM,       $000,  $100
PolitoedCryHeader:    cry_header CRY_GOLEM,       $000,  $100
HoppipCryHeader:      cry_header CRY_GOLEM,       $000,  $100
SkiploomCryHeader:    cry_header CRY_GOLEM,       $000,  $100
JumpluffCryHeader:    cry_header CRY_GOLEM,       $000,  $100
AipomCryHeader:       cry_header CRY_GOLEM,       $000,  $100
SunkernCryHeader:     cry_header CRY_GOLEM,       $000,  $100
SunfloraCryHeader:    cry_header CRY_GOLEM,       $000,  $100
YanmaCryHeader:       cry_header CRY_GOLEM,       $000,  $100
WooperCryHeader:      cry_header CRY_GOLEM,       $000,  $100
QuagsireCryHeader:    cry_header CRY_GOLEM,       $000,  $100
EspeonCryHeader:      cry_header CRY_GOLEM,       $000,  $100
UmbreonCryHeader:     cry_header CRY_GOLEM,       $000,  $100
MurkrowCryHeader:     cry_header CRY_GOLEM,       $000,  $100
SlowkingCryHeader:    cry_header CRY_GOLEM,       $000,  $100
MisdreavusCryHeader:  cry_header CRY_GOLEM,       $000,  $100
UnownCryHeader:       cry_header CRY_GOLEM,       $000,  $100
WobbuffetCryHeader:   cry_header CRY_GOLEM,       $000,  $100
GirafarigCryHeader:   cry_header CRY_GOLEM,       $000,  $100
PinecoCryHeader:      cry_header CRY_GOLEM,       $000,  $100
ForretressCryHeader:  cry_header CRY_GOLEM,       $000,  $100
DunsparceCryHeader:   cry_header CRY_GOLEM,       $000,  $100
GligarCryHeader:      cry_header CRY_GOLEM,       $000,  $100
SteelixCryHeader:     cry_header CRY_GOLEM,       $000,  $100
SnubbullCryHeader:    cry_header CRY_GOLEM,       $000,  $100
GranbullCryHeader:    cry_header CRY_GOLEM,       $000,  $100
QwilfishCryHeader:    cry_header CRY_GOLEM,       $000,  $100
ScizorCryHeader:      cry_header CRY_GOLEM,       $000,  $100
ShuckleCryHeader:     cry_header CRY_GOLEM,       $000,  $100
HeracrossCryHeader:   cry_header CRY_GOLEM,       $000,  $100
SneaselCryHeader:     cry_header CRY_GOLEM,       $000,  $100
TeddiursaCryHeader:   cry_header CRY_GOLEM,       $000,  $100
UrsaringCryHeader:    cry_header CRY_GOLEM,       $000,  $100
SlugmaCryHeader:      cry_header CRY_GOLEM,       $000,  $100
MagcargoCryHeader:    cry_header CRY_GOLEM,       $000,  $100
SwinubCryHeader:      cry_header CRY_GOLEM,       $000,  $100
PiloswineCryHeader:   cry_header CRY_GOLEM,       $000,  $100
CorsolaCryHeader:     cry_header CRY_GOLEM,       $000,  $100
RemoraidCryHeader:    cry_header CRY_GOLEM,       $000,  $100
OctilleryCryHeader:   cry_header CRY_GOLEM,       $000,  $100
DelibirdCryHeader:    cry_header CRY_GOLEM,       $000,  $100
MantineCryHeader:     cry_header CRY_GOLEM,       $000,  $100
SkarmoryCryHeader:    cry_header CRY_GOLEM,       $000,  $100
HoundourCryHeader:    cry_header CRY_GOLEM,       $000,  $100
HoundoomCryHeader:    cry_header CRY_GOLEM,       $000,  $100
KingdraCryHeader:     cry_header CRY_GOLEM,       $000,  $100
PhanpyCryHeader:      cry_header CRY_GOLEM,       $000,  $100
DonphanCryHeader:     cry_header CRY_GOLEM,       $000,  $100
Porygon2CryHeader:    cry_header CRY_GOLEM,       $000,  $100
StantlerCryHeader:    cry_header CRY_GOLEM,       $000,  $100
SmeargleCryHeader:    cry_header CRY_GOLEM,       $000,  $100
TyrogueCryHeader:     cry_header CRY_GOLEM,       $000,  $100
HitmontopCryHeader:   cry_header CRY_GOLEM,       $000,  $100
SmoochumCryHeader:    cry_header CRY_GOLEM,       $000,  $100
ElekidCryHeader:      cry_header CRY_GOLEM,       $000,  $100
MagbyCryHeader:       cry_header CRY_GOLEM,       $000,  $100
MiltankCryHeader:     cry_header CRY_GOLEM,       $000,  $100
BlisseyCryHeader:     cry_header CRY_GOLEM,       $000,  $100
RaikouCryHeader:      cry_header CRY_GOLEM,       $000,  $100
EnteiCryHeader:       cry_header CRY_GOLEM,       $000,  $100
SuicuneCryHeader:     cry_header CRY_GOLEM,       $000,  $100
LarvitarCryHeader:    cry_header CRY_GOLEM,       $000,  $100
PupitarCryHeader:     cry_header CRY_GOLEM,       $000,  $100
TyranitarCryHeader:   cry_header CRY_GOLEM,       $000,  $100
LugiaCryHeader:       cry_header CRY_GOLEM,       $000,  $100
HoOhCryHeader:        cry_header CRY_GOLEM,       $000,  $100
CelebiCryHeader:      cry_header CRY_GOLEM,       $000,  $100
CryHeader252:         cry_header CRY_NIDORAN_M,      0,     0
CryHeader253:         cry_header CRY_NIDORAN_M,      0,     0
CryHeader254:         cry_header CRY_NIDORAN_M,      0,     0
CryHeader255:         cry_header CRY_NIDORAN_M,      0,     0
; f2d81
