
TrainerPalettes: ; b0ce

PlayerPalette: ; b0ce
; The player's palette
;	RGB 25, 18, 12
;	RGB 22, 09, 05
	INCLUDE "gfx/pics/tangela/normal.pal"

KrisPalette: ; b0d0
; Kris uses Falkner's palette
;	RGB 27, 17, 14
;	RGB 07, 05, 31

FalknerPalette:      INCLUDE "gfx/pics/tangela/normal.pal"
WhitneyPalette:      INCLUDE "gfx/pics/tangela/normal.pal"
BugsyPalette:        INCLUDE "gfx/pics/tangela/normal.pal"
MortyPalette:        INCLUDE "gfx/pics/tangela/normal.pal"
PrycePalette:        INCLUDE "gfx/pics/tangela/normal.pal"
JasminePalette:      INCLUDE "gfx/pics/tangela/normal.pal"
ChuckPalette:        INCLUDE "gfx/pics/tangela/normal.pal"
ClairPalette:        INCLUDE "gfx/pics/tangela/normal.pal"
Rival1Palette:       INCLUDE "gfx/pics/tangela/normal.pal"
PokemonProfPalette:  INCLUDE "gfx/pics/tangela/normal.pal"
WillPalette:         INCLUDE "gfx/pics/tangela/normal.pal"
CalPalette:          INCLUDE "gfx/pics/tangela/normal.pal"
BrunoPalette:        INCLUDE "gfx/pics/tangela/normal.pal"
KarenPalette:        INCLUDE "gfx/pics/tangela/normal.pal"
KogaPalette:         INCLUDE "gfx/pics/tangela/normal.pal"
ChampionPalette:     INCLUDE "gfx/pics/tangela/normal.pal"
BrockPalette:        INCLUDE "gfx/pics/tangela/normal.pal"
MistyPalette:        INCLUDE "gfx/pics/tangela/normal.pal"
LtSurgePalette:      INCLUDE "gfx/pics/tangela/normal.pal"
ScientistPalette:    INCLUDE "gfx/pics/tangela/normal.pal"
ErikaPalette:        INCLUDE "gfx/pics/tangela/normal.pal"
YoungsterPalette:    INCLUDE "gfx/pics/tangela/normal.pal"
SchoolboyPalette:    INCLUDE "gfx/pics/tangela/normal.pal"
BirdKeeperPalette:   INCLUDE "gfx/pics/tangela/normal.pal"
LassPalette:         INCLUDE "gfx/pics/tangela/normal.pal"
JaninePalette:       INCLUDE "gfx/pics/tangela/normal.pal"
CooltrainermPalette: INCLUDE "gfx/pics/tangela/normal.pal"
CooltrainerfPalette: INCLUDE "gfx/pics/tangela/normal.pal"
BeautyPalette:       INCLUDE "gfx/pics/tangela/normal.pal"
PokemaniacPalette:   INCLUDE "gfx/pics/tangela/normal.pal"
GruntmPalette:       INCLUDE "gfx/pics/tangela/normal.pal"
GentlemanPalette:    INCLUDE "gfx/pics/tangela/normal.pal"
SkierPalette:        INCLUDE "gfx/pics/tangela/normal.pal"
TeacherPalette:      INCLUDE "gfx/pics/tangela/normal.pal"
SabrinaPalette:      INCLUDE "gfx/pics/tangela/normal.pal"
BugCatcherPalette:   INCLUDE "gfx/pics/tangela/normal.pal"
FisherPalette:       INCLUDE "gfx/pics/tangela/normal.pal"
SwimmermPalette:     INCLUDE "gfx/pics/tangela/normal.pal"
SwimmerfPalette:     INCLUDE "gfx/pics/tangela/normal.pal"
SailorPalette:       INCLUDE "gfx/pics/tangela/normal.pal"
SuperNerdPalette:    INCLUDE "gfx/pics/tangela/normal.pal"
Rival2Palette:       INCLUDE "gfx/pics/tangela/normal.pal"
GuitaristPalette:    INCLUDE "gfx/pics/tangela/normal.pal"
HikerPalette:        INCLUDE "gfx/pics/tangela/normal.pal"
BikerPalette:        INCLUDE "gfx/pics/tangela/normal.pal"
BlainePalette:       INCLUDE "gfx/pics/tangela/normal.pal"
BurglarPalette:      INCLUDE "gfx/pics/tangela/normal.pal"
FirebreatherPalette: INCLUDE "gfx/pics/tangela/normal.pal"
JugglerPalette:      INCLUDE "gfx/pics/tangela/normal.pal"
BlackbeltTPalette:   INCLUDE "gfx/pics/tangela/normal.pal"
ExecutivemPalette:   INCLUDE "gfx/pics/tangela/normal.pal"
PsychicTPalette:     INCLUDE "gfx/pics/tangela/normal.pal"
PicnickerPalette:    INCLUDE "gfx/pics/tangela/normal.pal"
CamperPalette:       INCLUDE "gfx/pics/tangela/normal.pal"
ExecutivefPalette:   INCLUDE "gfx/pics/tangela/normal.pal"
SagePalette:         INCLUDE "gfx/pics/tangela/normal.pal"
MediumPalette:       INCLUDE "gfx/pics/tangela/normal.pal"
BoarderPalette:      INCLUDE "gfx/pics/tangela/normal.pal"
PokefanmPalette:     INCLUDE "gfx/pics/tangela/normal.pal"
KimonoGirlPalette:   INCLUDE "gfx/pics/tangela/normal.pal"
TwinsPalette:        INCLUDE "gfx/pics/tangela/normal.pal"
PokefanfPalette:     INCLUDE "gfx/pics/tangela/normal.pal"
RedPalette:          INCLUDE "gfx/pics/tangela/normal.pal"
BluePalette:         INCLUDE "gfx/pics/tangela/normal.pal"
OfficerPalette:      INCLUDE "gfx/pics/tangela/normal.pal"
GruntfPalette:       INCLUDE "gfx/pics/tangela/normal.pal"
MysticalmanPalette:  INCLUDE "gfx/pics/tangela/normal.pal"
; b1de
